### ISSUE TITLE
What is the setup of Prisma?

### ISSUE THREAD

**Issue by redefinered** [jgeschwendt/serverless-prisma#1173]
And what would be the value for PRISMA_ENDPOINT in the .env file?

**Comment by redefinered** [comment]
Does Prisma run as a Lambda function here too?

**Comment by jgeschwendt** [comment]
The `PRISMA_ENDPOINT` is the URL of your hosted Prisma service. This project is just a template to use that service to build a GraphQL API which does run on lambda.

**Comment by redefinered** [comment]
Then why is the repo called “serverless-prisma”?

**Comment by jgeschwendt** [comment]
The project uses the Serverless Framework for pretty much everything and uses Prisma NPM modules as its API data source.

**Comment by redefinered** [comment]
If Prisma runs on a server, e.g. Prisma Cloud, Docker, droplet, or a Docker enabled hosting server like EC2 then this package should not be called "serverless-prisma" because it can be confusing. I think it should be something like serverless+prisma

**Comment by jamesburnersmith** [comment]
strongly agree.  super interesting title, way less relevant content!
