### ISSUE TITLE
Shouldn't context return value have the key db instead of prisma? 

### ISSUE THREAD

**Issue by steve-a-jones** [jgeschwendt/serverless-prisma#5]
https://github.com/jgeschwendt/serverless-prisma/blob/0d86fd072aaa2c558eac3d26b8c019ad14b651c4/src/graphql.ts#L10

I'm struggling the get this example working -- I am able to deploy, but seeing a lot of `TypeError: Cannot read property 'query' of undefined` errors in serverless logs. I'm wondering if this is due to incorrect instantiation of `Prisma`

**Comment by jgeschwendt** [comment]
You should be able to name the key whatever you want. Can you check your resolver to make sure that it's not referencing something other that `prisma`?
https://github.com/jgeschwendt/serverless-prisma/blob/master/src/resolvers/Query/index.ts#L3

**Comment by steve-a-jones** [comment]
Ah yes! You're correct - I failed to see how they connected .. I was able to get this working. I was using some boilerplate prisma code that used `context.db` which resulting in the failure.
