### ISSUE TITLE
Error when compiling with tsc

### ISSUE THREAD

**Issue by joelseq** [jgeschwendt/serverless-prisma#8]
Thank you so much creating this repository! I've been trying to use it to deploy my own lambda but I ran into this error when I ran the command `ENV=prod make deploy-api`:

![image](https://user-images.githubusercontent.com/12389411/38180552-4b182016-35e2-11e8-847f-6a57d94c0fe6.png)

I checked to make sure and I do have a `schema.graphql` inside `src/schema` and the relative path seems to be correct but it still won't compile. Any help you can offer on this would be greatly appreciated 😊

**Comment by jgeschwendt** [comment]
Thanks for reporting this. It's fixed with this commit – https://github.com/jgeschwendt/serverless-prisma/commit/8e4cd67936e415749149eb4658c4415e28905b05

What it was missing was the declaration for graphql files.
```typescript
declare module '*.graphql' {
  const content: any
  export default content
}
```
